import os

# Path Constants
PROGRAM_PATH = os.path.dirname( __file__ )
CONTROLLER_PATH = os.path.split( PROGRAM_PATH )[0]
PROJECT_PATH = os.path.split( os.path.split( PROGRAM_PATH )[0] )[0]

# Program Storage I/O
LAST_ID_FILE = os.path.join( CONTROLLER_PATH, 'data/last.id' )
SAVED_DATA_FILE = os.path.join( CONTROLLER_PATH, 'data/saved_data.txt' )

# Sensor I/O
LASER_RANGE_FINDER_INPUT_FILE = os.path.join( PROJECT_PATH, 'shared/data/lrf60m_10ph.in' )
LASER_RANGE_FINDER_OUTPUT_FILE = os.path.join( PROJECT_PATH, 'shared/data/lrf60m_10ph.out' )
INCLINOMETER_INPUT_FILE = os.path.join( PROJECT_PATH, 'shared/data/hwt905_ttl.in' )
INCLINOMETER_OUTPUT_FILE = os.path.join( PROJECT_PATH, 'shared/data/hwt905_ttl.out' )
MAGNETOMETER_INPUT_FILE = os.path.join( PROJECT_PATH, 'shared/data/hwt905_ttl.in' )
MAGNETOMETER_OUTPUT_FILE = os.path.join( PROJECT_PATH, 'shared/data/hwt905_ttl.out' )

# Laser Range Finder Commands
LRF_READ_SLAVE_ADDRESS = "AA 00 04 04 A8"
LRF_SET_SLAVE_COMMAND_ADDRESS = "AA 00 41 01 42 A8"
LRF_LASER_ON_COMMAND = "AA 01 42 43 A8"
LRF_LASER_OFF_COMMAND = "AA 01 43 44 A8"
LRF_SINGLE_MEASUREMENT_COMMAND = "AA 01 44 45 A8"

# Inclinometer Commands
INCLINOMETER_UNLOCK_COMMAND = "FF AA 69 88 B5"
INCLINOMETER_READ_PITCH_COMMAND = "FF AA 27 3E 00"

# Magnetometer Commands
MAGNETOMETER_UNLOCK_COMMAND = "FF AA 69 88 B5"
MAGNETOMETER_READ_MAGNETIC_X = "FF AA 27 3A 00"
MAGNETOMETER_READ_MAGNETIC_Y = "FF AA 27 3B 00"
MAGNETOMETER_READ_MAGNETIC_Z = "FF AA 27 3C 00"
MAGNETOMETER_READ_ACCELERATION_X = "FF AA 27 34 00"
MAGNETOMETER_READ_ACCELERATION_Y = "FF AA 27 35 00"
MAGNETOMETER_READ_ACCELERATION_Z = "FF AA 27 36 00"
MAGNETOMETER_ACCELEROMETER_CALIBRATION_COMMAND = "FF AA 01 03 00"
MAGNETOMETER_MAGNETIC_FIELD_CALIBRATION_COMMAND = "FF AA 01 07 00"
MAGNETOMETER_END_CALIBRATION_COMMAND = "FF AA 01 00 00"
MAGNETOMETER_SAVE_CALIBRATION_COMMAND = "FF AA 00 00 00"

# Compass Constants
NORTHEAST = ['NE', 45]
EAST = ['E', 90]
SOUTHEAST = ['SE', 135]
SOUTH = ['S', 180]
SOUTHWEST = ['SW', 225]
WEST = ['W', 270]
NORTHWEST = ['NW', 315]
NORTH = ['N', 360, 0]
HEADINGS = [ NORTHEAST, EAST, SOUTHEAST, SOUTHWEST, WEST, NORTHWEST, NORTH ]


